swagger: "2.0"
info:
  description: "Mock endpoints swagger"
  version: "1.0.0"
  title: "Mock API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/v1"
tags:
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /v1/weather:
    get:
      tags:
      - "user"
      summary: "Returns current temperature"
      description: ""
      operationId: "getWeather"
      produces:
      - "application/json"
      parameters:
      - name: "q"
        in: "query"
        description: "City name, state code and country code divided by comma, Please, refer to ISO 3166 for the state codes or country codes. You can specify the parameter not only in English. In this case, the API response should be returned in the same language as the language of requested location name if the location is in our predefined list of more than 200,000 locations."
        required: true
        type: "string"
      - name: "appid"
        in: "query"
        description: "Your unique API key"
        required: true
        type: "string"
      - name: "mode"
        in: "query"
        description: "Response format. Possible values are xml and html. If you don't use the mode parameter format is JSON by default."
        required: false
        type: "string"
      - name: "units"
        in: "query"
        description: "Units of measurement. standard, metric and imperial units are available. If you do not use the units parameter, standard units will be applied by default."
        required: false
        type: "string"
      - name: "lang"
        in: "query"
        description: "You can use this parameter to get the output in your language."
        required: false
        type: "string"
      responses:
        "200":
          description: "successful operation"
          examples:
            application/json:
              coord:
                lon: -123.262
                lat: 44.5646
              weather:
                - id: 804
                  main: Clouds
                  description: overcast clouds
                  icon: 04d
              base: stations
              main:
                temp: 282
                feels_like: 282
                temp_min: 280.02
                temp_max: 284.57
                pressure: 1027
                humidity: 77
              visibility: 10000
              wind:
                speed: 0
                deg: 0
              clouds:
                all: 100
              dt: 1642198763
              sys:
                type: 2
                id: 2040223
                country: US
                sunrise: 1642175199
                sunset: 1642208235
              timezone: -28800
              id: 5720727
              name: Corvallis
              cod: 200
        "400":
          description: "Invalid q/appid"
  /v1/hello:
    get:
      tags:
      - "user"
      summary: "Returns a warmful greeting"
      description: ""
      operationId: "getGreeting"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          examples:
            application/json:
              message: Hello
  /v1/auth:
    post:
      tags:
      - "user"
      summary: "Authenticate user and return token"
      consumes:
        - application/json
      description: ""
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "The user to login"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "successful operation"
          examples:
            application/json:
              token: 01232454r585u4u
definitions:
  User:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
  
  